#ifndef GPIO_DEFINITIONS_H
#define GPIO_DEFINITIONS_H

#include <stdint.h>

// GPIOx PORTx BASE ADDRESSES.
#define GPIOA_BASE 		0x40010800
#define GPIOB_BASE 		0x40010C00
#define GPIOC_BASE 		0x40011000
#define GPIOD_BASE 		0x40011400
#define GPIOE_BASE 		0x40011800
#define GPIOF_BASE 		0x40011C00
#define GPIOG_BASE 		0x40012000

// GPIO PORT SETTINGS (PAGE 171-174).
#define GPIOx_CRL_OFFSET	0x00 	// PORT CONFIGURATION REGISTER LOW
#define GPIOx_CRH_OFFSET 	0x04	// PORT CONFIGURATION REGISTER HIGH
#define GPIOx_IDR_OFFSET 	0x08	// PORT INPUT DATA REGISTER
#define GPIOx_ODR_OFFSET 	0x0C	// PORT OUTPUT DATA REGISTER
#define GPIOx_BSRR_OFFSET 	0x10	// PORT BIT SET/RESET REGISTER
#define GPIOx_BRR_OFFSET 	0x14	// PORT BIT RESET REGISTER
#define GPIOx_LCKR_OFFSET 	0x18	// PORT CONFIG LOCK REGISTER

// GIVEN A BASE GPIO ADDRESS, GPIO NUM, CNF AND MOD STRINGS,SETS THE CRH REGISTER.;
void set_gpio_crh(uint32_t GPIOx_ADDR, uint8_t CNF, uint8_t MOD, uint8_t GPIO_NUM);

#endif